import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="hero"
        className="min-h-screen  w-full px-5 md:px-10 xl:px-0 flex justify-center pt-10 pb-5 relative "
      >
        <div className="max-w-7xl w-full h-full relative grid grid-cols-3 gap-4">
          <form className="flex flex-col gap-4 rounded-md border p-4">
            <div className="bg-[#E6E6E6] w-full p-4 flex flex-col gap-4">
              <div className="flex gap-4">
                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <svg
                    width="20"
                    height="25"
                    viewBox="0 0 20 25"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M9.87499 0C7.3896 0.00329693 5.00695 0.992075 3.24951 2.74951C1.49207 4.50695 0.503297 6.8896 0.5 9.37499C0.5 16.1055 9.23437 24.5351 9.60546 24.8906C9.67764 24.9608 9.77433 25 9.87499 25C9.97565 25 10.0723 24.9608 10.1445 24.8906C10.5156 24.5351 19.25 16.1055 19.25 9.37499C19.2467 6.8896 18.2579 4.50695 16.5005 2.74951C14.743 0.992075 12.3604 0.00329693 9.87499 0V0ZM9.87499 13.6719C9.02515 13.6719 8.19439 13.4199 7.48778 12.9477C6.78116 12.4756 6.23042 11.8045 5.9052 11.0193C5.57998 10.2342 5.49489 9.37022 5.66068 8.53671C5.82648 7.7032 6.23572 6.93757 6.83664 6.33664C7.43757 5.73572 8.2032 5.32648 9.03671 5.16068C9.87022 4.99489 10.7342 5.07998 11.5193 5.4052C12.3045 5.73042 12.9756 6.28116 13.4477 6.98778C13.9199 7.69439 14.1719 8.52515 14.1719 9.37499C14.1712 10.5144 13.7183 11.6069 12.9126 12.4126C12.1069 13.2183 11.0144 13.6712 9.87499 13.6719Z"
                      fill="currentColor"
                    />
                  </svg>

                  <p className="text-xs text-center">Location</p>
                </div>

                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <svg
                    width="20"
                    height="25"
                    viewBox="0 0 20 25"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M10 0.5C4.475 0.5 0 1.125 0 5.5V17.375C0 19.7875 1.9625 21.75 4.375 21.75L2.5 23.625V24.25H17.5V23.625L15.625 21.75C18.0375 21.75 20 19.7875 20 17.375V5.5C20 1.125 15.525 0.5 10 0.5ZM4.375 19.25C3.3375 19.25 2.5 18.4125 2.5 17.375C2.5 16.3375 3.3375 15.5 4.375 15.5C5.4125 15.5 6.25 16.3375 6.25 17.375C6.25 18.4125 5.4125 19.25 4.375 19.25ZM8.75 11.75H2.5V5.5H8.75V11.75ZM15.625 19.25C14.5875 19.25 13.75 18.4125 13.75 17.375C13.75 16.3375 14.5875 15.5 15.625 15.5C16.6625 15.5 17.5 16.3375 17.5 17.375C17.5 18.4125 16.6625 19.25 15.625 19.25ZM17.5 11.75H11.25V5.5H17.5V11.75Z"
                      fill="currentColor"
                    />
                  </svg>

                  <p className="text-xs text-center">Transport</p>
                </div>

                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <div className="shrink-0">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M18.25 10.75V0.75H5.75V5.75H0.75V23.25H10.75V18.25H13.25V23.25H23.25V10.75H18.25ZM5.75 20.75H3.25V18.25H5.75V20.75ZM5.75 15.75H3.25V13.25H5.75V15.75ZM5.75 10.75H3.25V8.25H5.75V10.75ZM10.75 15.75H8.25V13.25H10.75V15.75ZM10.75 10.75H8.25V8.25H10.75V10.75ZM10.75 5.75H8.25V3.25H10.75V5.75ZM15.75 15.75H13.25V13.25H15.75V15.75ZM15.75 10.75H13.25V8.25H15.75V10.75ZM15.75 5.75H13.25V3.25H15.75V5.75ZM20.75 20.75H18.25V18.25H20.75V20.75ZM20.75 15.75H18.25V13.25H20.75V15.75Z"
                        fill="currentColor"
                      />
                    </svg>
                  </div>

                  <p className="text-xs text-center">Industrial Estates</p>
                </div>
              </div>

              <div className="flex flex-col gap-2">
                <label htmlFor="location" className="font-bold">
                  Location<span className="text-red-600">*</span>:
                </label>

                <input
                  type="text"
                  name="location"
                  id="location"
                  className="px-4 py-2 w-full rounded-md"
                />

                <div className="inline-flex gap-2">
                  <input id="nearme" type="checkbox" />
                  <label htmlFor="nearme" className="font-bold">
                    Near Me
                  </label>
                </div>
              </div>
            </div>

            <div className="bg-white w-full p-4 flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="function" className="font-bold">
                    Job Function:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="function"
                  id="function"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="Business" className="font-bold">
                    Business Industry:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="Business"
                  id="Business"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="Keywords" className="font-bold">
                    Keywords:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="Keywords"
                  id="Keywords"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex gap-4 items-center">
                <div className="flex items-center">
                  <input
                    id="default-radio-1"
                    type="radio"
                    value=""
                    name="default-radio"
                    className="w-4 h-4 text-[#82170F] bg-gray-100 border-gray-300 accent-[#82170F] "
                  />

                  <label
                    htmlFor="default-radio-1"
                    className="ml-2 text-sm font-medium "
                  >
                    Match all words
                  </label>
                </div>

                <div className="flex items-center">
                  <input
                    checked
                    id="default-radio-2"
                    type="radio"
                    value=""
                    name="default-radio"
                    className="w-4 h-4 text-[#82170F] bg-gray-100 border-gray-300 accent-[#82170F]"
                  />
                  <label
                    htmlFor="default-radio-2"
                    className="ml-2 text-sm font-medium "
                  >
                    Match any words
                  </label>
                </div>
              </div>

              <div className="flex justify-end text-left">
                <p className="underline-offset-2 text-[#82170F]">
                  Advance Search
                </p>
              </div>
            </div>

            <button
              type="submit"
              title="submit"
              className="py-2 px-4 w-full text-white text-center bg-[#82170F] rounded-md "
            >
              Search
            </button>
          </form>

          <div className=" col-span-2 w-full h-full relative flex flex-col">
            <div className="h-4/5 w-full bg-slate-500 "></div>

            <div className="flex-1 grid grid-cols-3 gap-4">
              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/document.svg" alt="document" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Share your resume</p>
                  <p className="text-sm ">
                    กรุณาฝากประวัติเพื่อให้ระบบแนะนำตำแหน่งงานที่เหมาะสมโดยไม่ต้องค้นหา
                  </p>
                </div>
              </div>

              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/mail.svg" alt="mail" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Get Job Alert</p>
                  <p className="text-sm ">
                    สร้างการแจ้งเตือนเมื่อมีงานที่ตรงกับความสนใจของคุณผ่านระบบ
                    Job Alert
                  </p>
                </div>
              </div>

              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/desktop.svg" alt="desktop" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Free Language Test</p>
                  <p className="text-sm ">
                    ทดสอบทักษะภาษาอังกฤษของคุณเพื่อเปิดโอกาสให้บริษัทชั้นนำได้ค้นพบความสามารถของท่าน
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Premium Companies</h1>
              <p>
                โอกาสก้าวหน้ากับบริษัทชั้นนำ
                รวมตำแหน่งงานเด่นที่พร้อมให้คุณเข้ามาเป็นส่วนหนึ่ง
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Top Recriutors</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Faucibus aliquam quisque risus.
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Recent Jobs</h1>
              <p>ตำแหน่งงานล่าสุด อัพเดทตลอด 24 ชั่วโมง ทุกวัน</p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Browse Jobs</h1>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Updates</h1>
              <p>
                ไม่พลาดทุกข่าวสาร เคล็ดลับ บทความ ที่จะเปิดโลกการทำงานใหม่ๆ
                ที่เราคัดสรรมาเพื่อคุณ
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Tips & Tricks</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus
                venenatis, eu, tincidunt curabitur amet. Sed.
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
