import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import React, { FC, useEffect, useState, Fragment } from "react";
import { Tab } from "@headlessui/react";

function classNames(...classes: any[]) {
  return classes.filter(Boolean).join(" ");
}

const job_function = [
  { id: 1, name: "Accounting" },
  { id: 2, name: "Admin / HR" },
  { id: 4, name: "Banking / Finance" },
  { id: 5, name: "Building / Construction" },
  { id: 6, name: "Business Consulting" },
  { id: 7, name: "Design" },
  { id: 8, name: "Education / Language" },
  { id: 9, name: "Engineering" },
  { id: 10, name: "Hospitality / Tourism / F&B / Hotel" },
  { id: 11, name: "Insurance Related" },
  { id: 12, name: "Interpreter / Translator" },
  { id: 13, name: "IT Related" },
  { id: 14, name: "Logistic / Transportation" },
  { id: 15, name: "Management" },
  { id: 16, name: "Manufacturing / Industrial Engineering" },
  { id: 17, name: "Marketing / PR" },
  { id: 18, name: "Media / Advertising" },
  { id: 19, name: "Medical / Nursing / Health Related" },
  { id: 20, name: "Merchandising / Sourcing Agent" },
  { id: 21, name: "Property / Real Estate" },
  { id: 22, name: "Sales / Customer Service / Call Center" },
  { id: 23, name: "Others" },
];

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="hero"
        className=" w-full px-5 md:px-10 xl:px-0 flex justify-center pt-10 pb-5 relative "
      >
        <div className="max-w-7xl w-full h-full relative grid grid-cols-1 lg:grid-cols-3 gap-4 justify-items-center">
          <form className="flex flex-col gap-4 rounded-md border p-4 w-full">
            <div className="bg-[#E6E6E6] w-full p-4 flex flex-col gap-4">
              <div className="flex gap-4">
                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <svg
                    width="20"
                    height="25"
                    viewBox="0 0 20 25"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M9.87499 0C7.3896 0.00329693 5.00695 0.992075 3.24951 2.74951C1.49207 4.50695 0.503297 6.8896 0.5 9.37499C0.5 16.1055 9.23437 24.5351 9.60546 24.8906C9.67764 24.9608 9.77433 25 9.87499 25C9.97565 25 10.0723 24.9608 10.1445 24.8906C10.5156 24.5351 19.25 16.1055 19.25 9.37499C19.2467 6.8896 18.2579 4.50695 16.5005 2.74951C14.743 0.992075 12.3604 0.00329693 9.87499 0V0ZM9.87499 13.6719C9.02515 13.6719 8.19439 13.4199 7.48778 12.9477C6.78116 12.4756 6.23042 11.8045 5.9052 11.0193C5.57998 10.2342 5.49489 9.37022 5.66068 8.53671C5.82648 7.7032 6.23572 6.93757 6.83664 6.33664C7.43757 5.73572 8.2032 5.32648 9.03671 5.16068C9.87022 4.99489 10.7342 5.07998 11.5193 5.4052C12.3045 5.73042 12.9756 6.28116 13.4477 6.98778C13.9199 7.69439 14.1719 8.52515 14.1719 9.37499C14.1712 10.5144 13.7183 11.6069 12.9126 12.4126C12.1069 13.2183 11.0144 13.6712 9.87499 13.6719Z"
                      fill="currentColor"
                    />
                  </svg>

                  <p className="text-xs text-center">Location</p>
                </div>

                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <svg
                    width="20"
                    height="25"
                    viewBox="0 0 20 25"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M10 0.5C4.475 0.5 0 1.125 0 5.5V17.375C0 19.7875 1.9625 21.75 4.375 21.75L2.5 23.625V24.25H17.5V23.625L15.625 21.75C18.0375 21.75 20 19.7875 20 17.375V5.5C20 1.125 15.525 0.5 10 0.5ZM4.375 19.25C3.3375 19.25 2.5 18.4125 2.5 17.375C2.5 16.3375 3.3375 15.5 4.375 15.5C5.4125 15.5 6.25 16.3375 6.25 17.375C6.25 18.4125 5.4125 19.25 4.375 19.25ZM8.75 11.75H2.5V5.5H8.75V11.75ZM15.625 19.25C14.5875 19.25 13.75 18.4125 13.75 17.375C13.75 16.3375 14.5875 15.5 15.625 15.5C16.6625 15.5 17.5 16.3375 17.5 17.375C17.5 18.4125 16.6625 19.25 15.625 19.25ZM17.5 11.75H11.25V5.5H17.5V11.75Z"
                      fill="currentColor"
                    />
                  </svg>

                  <p className="text-xs text-center">Transport</p>
                </div>

                <div className="w-32 h-16 bg-white rounded p-2 flex flex-col gap-1 justify-center items-center text-[#B3B3B3] hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 cursor-pointer">
                  <div className="shrink-0">
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M18.25 10.75V0.75H5.75V5.75H0.75V23.25H10.75V18.25H13.25V23.25H23.25V10.75H18.25ZM5.75 20.75H3.25V18.25H5.75V20.75ZM5.75 15.75H3.25V13.25H5.75V15.75ZM5.75 10.75H3.25V8.25H5.75V10.75ZM10.75 15.75H8.25V13.25H10.75V15.75ZM10.75 10.75H8.25V8.25H10.75V10.75ZM10.75 5.75H8.25V3.25H10.75V5.75ZM15.75 15.75H13.25V13.25H15.75V15.75ZM15.75 10.75H13.25V8.25H15.75V10.75ZM15.75 5.75H13.25V3.25H15.75V5.75ZM20.75 20.75H18.25V18.25H20.75V20.75ZM20.75 15.75H18.25V13.25H20.75V15.75Z"
                        fill="currentColor"
                      />
                    </svg>
                  </div>

                  <p className="text-xs text-center">Industrial Estates</p>
                </div>
              </div>

              <div className="flex flex-col gap-2">
                <label htmlFor="location" className="font-bold">
                  Location<span className="text-red-600">*</span>:
                </label>

                <input
                  type="text"
                  name="location"
                  id="location"
                  className="px-4 py-2 w-full rounded-md"
                />

                <div className="inline-flex gap-2">
                  <input
                    id="nearme"
                    type="checkbox"
                    className="accent-[#82170F]"
                    defaultChecked={false}
                  />
                  <label htmlFor="nearme" className="font-bold">
                    Near Me
                  </label>
                </div>
              </div>
            </div>

            <div className="bg-white w-full p-4 flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="function" className="font-bold">
                    Job Function:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="function"
                  id="function"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="Business" className="font-bold">
                    text-sm Business Industry:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="Business"
                  id="Business"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex flex-col gap-2">
                <div className="flex justify-between">
                  <label htmlFor="Keywords" className="font-bold">
                    Keywords:
                  </label>

                  <p className="text-[#B3B3B3] text-sm">1/5</p>
                </div>

                <input
                  type="text"
                  name="Keywords"
                  id="Keywords"
                  className="px-4 py-2 w-full rounded-md border"
                />
              </div>

              <div className="flex gap-4 items-center">
                <div className="flex items-center">
                  <input
                    id="default-radio-1"
                    type="radio"
                    value=""
                    name="default-radio"
                    className="w-4 h-4 text-[#82170F] bg-gray-100 border-gray-300 accent-[#82170F]"
                    checked={true}
                    readOnly
                  />

                  <label
                    htmlFor="default-radio-1"
                    className="ml-2 text-sm font-medium "
                  >
                    Match all words
                  </label>
                </div>

                <div className="flex items-center">
                  <input
                    id="default-radio-2"
                    type="radio"
                    value=""
                    name="default-radio"
                    className="w-4 h-4 text-[#82170F] bg-gray-100 border-gray-300 accent-[#82170F]"
                  />
                  <label
                    htmlFor="default-radio-2"
                    className="ml-2 text-sm font-medium "
                  >
                    Match any words
                  </label>
                </div>
              </div>

              <div className="flex justify-end text-left">
                <p className="underline-offset-2 text-[#82170F]">
                  Advance Search
                </p>
              </div>
            </div>

            <button
              type="submit"
              title="submit"
              className="py-2 px-4 w-full text-white text-center bg-[#82170F] rounded-md "
            >
              Search
            </button>
          </form>

          <div className=" lg:col-span-2 w-full h-full relative flex flex-col">
            <div className="h-4/5 min-h-[500px] w-full relative bg-[url('/assets/Rectangle139.png')] bg-cover bg-right bg-no-repeat">
              {/* <Image src="/assets/Slider.png" alt="slide" fill /> */}
            </div>

            <div className="flex-1 grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/document.svg" alt="document" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Share your resume</p>
                  <p className="text-sm ">
                    กรุณาฝากประวัติเพื่อให้ระบบแนะนำตำแหน่งงานที่เหมาะสมโดยไม่ต้องค้นหา
                  </p>
                </div>
              </div>

              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/mail.svg" alt="mail" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Get Job Alert</p>
                  <p className="text-sm ">
                    สร้างการแจ้งเตือนเมื่อมีงานที่ตรงกับความสนใจของคุณผ่านระบบ
                    Job Alert
                  </p>
                </div>
              </div>

              <div className="w-full flex gap-4 relative p-4 items-center">
                <div className="shrink-0 w-16 h-16 text-[#82170F] relative">
                  <Image src="/assets/desktop.svg" alt="desktop" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <p className="font-bold">Free Language Test</p>
                  <p className="text-sm ">
                    ทดสอบทักษะภาษาอังกฤษของคุณเพื่อเปิดโอกาสให้บริษัทชั้นนำได้ค้นพบความสามารถของท่าน
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Premium Companies</h1>
              <p>
                โอกาสก้าวหน้ากับบริษัทชั้นนำ
                รวมตำแหน่งงานเด่นที่พร้อมให้คุณเข้ามาเป็นส่วนหนึ่ง
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>

          <div className="w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-5 gap-4">
            <div className="h-64 w-full py-4 flex flex-col gap-2">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0"></div>

              <div>
                <p className="font-bold">Company Name</p>
                <p className="text-black/70 text-sm">Business Industry</p>
              </div>
            </div>
            <div className="h-64 w-full py-4 flex flex-col gap-2">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0"></div>

              <div>
                <p className="font-bold">Company Name</p>
                <p className="text-black/70 text-sm">Business Industry</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 flex flex-col gap-2">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0"></div>

              <div>
                <p className="font-bold">Company Name</p>
                <p className="text-black/70 text-sm">Business Industry</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 xl:flex flex-col gap-2 hidden">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0"></div>

              <div>
                <p className="font-bold">Company Name</p>
                <p className="text-black/70 text-sm">Business Industry</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 xl:flex flex-col gap-2 hidden">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0"></div>

              <div>
                <p className="font-bold">Company Name</p>
                <p className="text-black/70 text-sm">Business Industry</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Top Recriutors</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Faucibus aliquam quisque risus.
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>

          <div className="w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-5 gap-4">
            <div className="h-64 w-full py-4 flex flex-col gap-2">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0  bg-[url('/assets/Frame1321315353.png')] bg-center bg-contain bg-no-repeat"></div>

              <div>
                <p className="font-bold">Recriutor Name</p>
              </div>
            </div>
            <div className="h-64 w-full py-4 flex flex-col gap-2 ">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0 bg-[url('/assets/Frame1321315353.png')] bg-center bg-contain bg-no-repeat"></div>

              <div>
                <p className="font-bold">Recriutor Name</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 flex flex-col gap-2 ">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0 bg-[url('/assets/Frame1321315353.png')] bg-center bg-contain bg-no-repeat"></div>

              <div>
                <p className="font-bold">Recriutor Name</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 xl:flex flex-col gap-2 hidden ">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0 bg-[url('/assets/Frame1321315353.png')] bg-center bg-contain bg-no-repeat"></div>

              <div>
                <p className="font-bold">Recriutor Name</p>
              </div>
            </div>

            <div className="h-64 w-full py-4 xl:flex flex-col gap-2 hidden ">
              <div className="h-44 w-full bg-[#F7F7F7] shrink-0 bg-[url('/assets/Frame1321315353.png')] bg-center bg-contain bg-no-repeat"></div>

              <div>
                <p className="font-bold">Recriutor Name</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Recent Jobs</h1>
              <p>ตำแหน่งงานล่าสุด อัพเดทตลอด 24 ชั่วโมง ทุกวัน</p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>

          <div className="w-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 ">
            {[...Array(6)].map((_, index) => (
              <div
                key={index}
                className="h-[300px] w-full rounded-xl border p-4 flex flex-col gap-4 relative "
              >
                <div className="flex gap-4">
                  <div className="h-20 w-20 shrink-0 relative">
                    <Image src="/assets/Icon.svg" alt="logo" fill />
                  </div>

                  <div className="flex-1">
                    <p className="font-bold ">
                      Senior engineer / Sales & Marketing
                    </p>
                    <p className="font-bold text-sm">บริษัท ไทยชินเมวา จำกัด</p>
                    <p className="text-sm">อ. เมืองชลบุรี จ. ชลบุรี</p>
                  </div>
                </div>

                <div className="flex flex-col gap-2 border-b pb-4">
                  <div className="flex gap-1 items-center ">
                    <div className="w-5 h-5  relative shrink-0 text-[#B3B3B3] flex items-center ">
                      <svg
                        width="17"
                        height="16"
                        viewBox="0 0 17 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M9.88411 10.0834C9.88411 10.3136 9.69766 10.5 9.46745 10.5H6.96745C6.73724 10.5 6.55078 10.3136 6.55078 10.0834V8.83335H1.55078V12.5834C1.55078 13.25 2.13411 13.8334 2.80078 13.8334H13.6341C14.3008 13.8334 14.8841 13.25 14.8841 12.5834V8.83335H9.88411V10.0834ZM13.6341 4.66669H11.5508V3.41669C11.5508 2.75002 10.9674 2.16669 10.3008 2.16669H6.13411C5.46745 2.16669 4.88411 2.75002 4.88411 3.41669V4.66669H2.80078C2.13411 4.66669 1.55078 5.25002 1.55078 5.91669V8.00002H14.8841V5.91669C14.8841 5.25002 14.3008 4.66669 13.6341 4.66669ZM9.88411 4.66669H6.55078V3.83335H9.88411V4.66669Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>
                    <p className="text-sm align-middle">Full-Time</p>
                  </div>

                  <div className="flex gap-1 items-center ">
                    <div className="w-5 h-5  relative shrink-0 text-[#B3B3B3] flex items-center ">
                      <svg
                        width="17"
                        height="16"
                        viewBox="0 0 17 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M11.8841 7.33335C10.2258 7.33335 8.88411 8.67502 8.88411 10.3334C8.88411 11.9917 10.2258 13.3334 11.8841 13.3334C13.5424 13.3334 14.8841 11.9917 14.8841 10.3334C14.8841 8.67502 13.5424 7.33335 11.8841 7.33335ZM13.2174 10.4646C13.2174 10.575 13.1258 10.6667 13.0154 10.6667H11.7529C11.6424 10.6667 11.5508 10.575 11.5508 10.4646V8.86877C11.5508 8.75835 11.6424 8.66669 11.7529 8.66669H12.0154C12.1258 8.66669 12.2174 8.75835 12.2174 8.86877V10H13.0154C13.1258 10 13.2174 10.0917 13.2174 10.2021V10.4646ZM8.21745 10.3334C8.21745 9.75419 8.35703 9.20627 8.59661 8.71877C8.42995 8.68752 8.25911 8.66669 8.08412 8.66669H7.7362C7.2737 8.87919 6.75911 9.00002 6.21745 9.00002C5.67578 9.00002 5.16328 8.87919 4.6987 8.66669H4.35078C2.80495 8.66669 1.55078 9.92085 1.55078 11.4667V12.3334C1.55078 12.8854 1.9987 13.3334 2.55078 13.3334H9.78203C8.83828 12.6688 8.21745 11.5729 8.21745 10.3334ZM6.21745 8.00002C7.69036 8.00002 8.88411 6.80627 8.88411 5.33335C8.88411 3.86044 7.69036 2.66669 6.21745 2.66669C4.74453 2.66669 3.55078 3.86044 3.55078 5.33335C3.55078 6.80627 4.74453 8.00002 6.21745 8.00002Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>

                    <p className="text-sm align-middle">
                      2 years+ of experiences
                    </p>
                  </div>

                  <div className="flex gap-1 items-center ">
                    <div className="w-5 h-5  relative shrink-0 text-[#B3B3B3] flex items-center ">
                      <svg
                        width="17"
                        height="16"
                        viewBox="0 0 17 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M13.5612 4.66669H3.63411C3.40391 4.66669 3.21745 4.48023 3.21745 4.25002C3.21745 4.01981 3.40391 3.83335 3.63411 3.83335H13.6341C13.8643 3.83335 14.0508 3.6469 14.0508 3.41669C14.0508 2.72632 13.4911 2.16669 12.8008 2.16669H3.21745C2.29688 2.16669 1.55078 2.91278 1.55078 3.83335V12.1667C1.55078 13.0873 2.29688 13.8334 3.21745 13.8334H13.5612C14.2909 13.8334 14.8841 13.2727 14.8841 12.5834V5.91669C14.8841 5.22736 14.2909 4.66669 13.5612 4.66669ZM12.3841 10.0834C11.924 10.0834 11.5508 9.71018 11.5508 9.25002C11.5508 8.78986 11.924 8.41669 12.3841 8.41669C12.8443 8.41669 13.2174 8.78986 13.2174 9.25002C13.2174 9.71018 12.8443 10.0834 12.3841 10.0834Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>

                    <p className="text-sm align-middle">Salary: 15,000 Baht฿</p>
                  </div>
                </div>

                <div id="jobtag" className="flex gap-2">
                  <button className="px-4 py-1 rounded-lg bg-[#F3F2F2] text-sm">
                    รับสมัครด่วน
                  </button>
                  <button className="px-4 py-1 rounded-lg bg-[#F3F2F2] text-sm">
                    งานยอดนิยม
                  </button>

                  <button className="px-4 py-1 rounded-lg bg-[#F3F2F2] text-sm">
                    Tag C
                  </button>
                </div>

                <p className="text-xs -translate-y-1">Post date: 6 Sep 2022</p>

                <button className="absolute top-4 right-4 w-11 h-11 bg-[#F3F2F2] rounded-md border flex justify-center items-center text-[#B3B3B3]">
                  <svg
                    width="18"
                    height="23"
                    viewBox="0 0 18 23"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M15.4062 0.5H3.03125C1.89215 0.5 0.96875 1.4234 0.96875 2.5625V22.5L9.21875 17.6875L17.4688 22.5V2.5625C17.4688 1.4234 16.5454 0.5 15.4062 0.5ZM15.4062 18.9091L9.21875 15.2997L3.03125 18.9091V2.82031C3.03125 2.75194 3.05841 2.68636 3.10676 2.63801C3.15511 2.58966 3.22069 2.5625 3.28906 2.5625H15.1484C15.2908 2.5625 15.4062 2.67779 15.4062 2.82014V18.9091Z"
                      fill="currentColor"
                    />
                  </svg>
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold">Browse Jobs</h1>
            </div>
          </div>

          <Tab.Group>
            <Tab.List>
              <Tab as={Fragment}>
                {({ selected }) => (
                  <button
                    className={classNames(
                      selected
                        ? "border-b-2 border-[#82170F] text-[#82170F] font-bold"
                        : "text-[#595959]",
                      "px-4 py-2 min-w-[170px] focus:ring-0 focus:outline-none"
                    )}
                  >
                    By Job Function
                  </button>
                )}
              </Tab>

              <Tab as={Fragment}>
                {({ selected }) => (
                  <button
                    className={classNames(
                      selected
                        ? "border-b-2 border-[#82170F] text-[#82170F] font-bold"
                        : "text-[#595959]",
                      "px-4 py-2 min-w-[170px] focus:ring-0 focus:outline-none"
                    )}
                  >
                    By Business Industry
                  </button>
                )}
              </Tab>

              <Tab as={Fragment}>
                {({ selected }) => (
                  <button
                    className={classNames(
                      selected
                        ? "border-b-2 border-[#82170F] text-[#82170F] font-bold"
                        : "text-[#595959]",
                      "px-4 py-2 min-w-[170px] focus:ring-0 focus:outline-none"
                    )}
                  >
                    By Location
                  </button>
                )}
              </Tab>
            </Tab.List>
            <Tab.Panels>
              <Tab.Panel
                className={
                  "w-full min-h-[350px] grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-2 justify-items-center"
                }
              >
                {job_function.map((item, index) => (
                  <button
                    key={index}
                    className="inline-flex items-center justify-center w-full p-2 border rounded-md  hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 text-sm "
                  >
                    {item.name}
                  </button>
                ))}
              </Tab.Panel>

              <Tab.Panel
                className={
                  "w-full min-h-[350px] grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-2 justify-items-center"
                }
              >
                {job_function.map((item, index) => (
                  <button
                    key={index}
                    className="inline-flex items-center justify-center w-full p-2 border rounded-md  hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 text-sm "
                  >
                    {item.name}
                  </button>
                ))}
              </Tab.Panel>

              <Tab.Panel
                className={
                  "w-full min-h-[350px] grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-2 justify-items-center"
                }
              >
                {job_function.map((item, index) => (
                  <button
                    key={index}
                    className="inline-flex items-center justify-center w-full p-2 border rounded-md  hover:bg-[#EEEEDD] hover:text-[#82170F] hover:border-[#82170F] hover:border duration-300 text-sm "
                  >
                    {item.name}
                  </button>
                ))}
              </Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-44 relative gap-4 flex bg-[#F3F2F2] justify-center items-center ">
          <p className="font-bold">Banner Leaderboard</p>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5  relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center border-b pb-4">
            <div>
              <h1 className="text-3xl font-bold">Updates</h1>
              <p>
                ไม่พลาดทุกข่าวสาร เคล็ดลับ บทความ ที่จะเปิดโลกการทำงานใหม่ๆ
                ที่เราคัดสรรมาเพื่อคุณ
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>

          <div className="w-full grid grid-cols-1 md:grid-cols-3 gap-4 ">
            {[...Array(3)].map((_, index) => (
              <div
                key={index}
                className="h-[432px]  w-full rounded-xl  flex flex-col gap-4 relative"
              >
                <div className="h-3/5 w-full relative">
                  <Image src="/assets/Rectangle628.png" alt="desktop" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <div className="px-2 py-1 rounded bg-[#EEEEDD] flex justify-center items-center text-xs w-fit">
                    EVENT
                  </div>

                  <p className="font-bold">
                    Event - Lorem ipsum dolor sit amet, consectetur adipiscing
                    elit
                  </p>

                  <p className="text-[#595959] text-sm">
                    Now it’s comes handy with Categories, just look up what
                    career you want to
                  </p>
                  <p className="text-[#595959] text-sm">08/09/2022</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="w-full px-5 md:px-10 xl:px-0 flex justify-center py-5 pb-10 relative">
        <div className="max-w-7xl w-full h-full relative gap-4 flex flex-col">
          <div className="flex justify-between items-center border-b pb-4">
            <div>
              <h1 className="text-3xl font-bold">Tips & Tricks</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus
                venenatis, eu, tincidunt curabitur amet. Sed.
              </p>
            </div>

            <div className="shrink-0">
              <p className="text-[#82170F]">View All</p>
            </div>
          </div>

          <div className="w-full grid grid-cols-1 md:grid-cols-3 gap-4 ">
            {[...Array(3)].map((_, index) => (
              <div
                key={index}
                className="h-[432px]  w-full rounded-xl  flex flex-col gap-4 relative"
              >
                <div className="h-3/5 w-full relative">
                  <Image src="/assets/Rectangle628.png" alt="desktop" fill />
                </div>

                <div className="flex flex-col gap-1">
                  <div className="px-2 py-1 rounded bg-[#EEEEDD] flex justify-center items-center text-xs w-fit">
                    Life@work
                  </div>

                  <p className="font-bold">
                    Blog Title - Lorem ipsum dolor sit amet, consectetur
                    adipiscing elit
                  </p>

                  <p className="text-[#595959] text-sm">
                    Now it’s comes handy with Categories, just look up what
                    career you want to
                  </p>
                  <p className="text-[#595959] text-sm">08/09/2022</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
